### ISSUE TITLE
Interfaces

### ISSUE THREAD

**Issue by jmartin84** [shibbybird/eazy-ci#1]
so for emsci I tried to put most of the docker stuff behind [interfaces](https://github.com/jmartin84/emsci/blob/master/runtime/types/types.go) to make it easier to potentially support other container runtimes in the future.

You interested in me porting that over?

**Comment by shibbybird** [comment]
Actually I was thinking the exact thing. I wanted the next runtime/orchestrator to be kubernetes because everything has mini kube now. I haven't thought how to handle the deployment config, but if you reworked the docker stuff into interfaces I would totally merge. Good suggestion. Having a kubernetes as the orchestrator would allow for large scale system tests though. Which would be really interesting.

**Comment by jmartin84** [comment]
ohh, I didn't even think about k8s - just a custom flavor of runc or rkt or something. native k8s support would be killer.

**Comment by jmartin84** [comment]
``` I haven't thought how to handle the deployment config```

I'm not sure it would be all that different, really. If you have the image/port info you can more or less spin up all the pods and services. If anything k8s gives you more flexibility because you can more easily run pre/post container start up tasks using k8s jobs. 

Since a given CI run is basically a short lived one-off, I don't think you really need to worry about creating deployments, daemons, replica sets, etc and just stick to pods and jobs. Additionally each ci "run" could be scoped to its own namespace with the option to not destroy any resources after the run completes to give users an extra layer of potential insight into any issues they are having. Lots of neat potential in k8s.

**Comment by shibbybird** [comment]
Agreed that would be a good first step. The one thing that would be nice to come out of that work is at least the potential to scale up multiple pods on a deployment. Lots of issues aren't noticed in distributed systems when you test with one. It would at least be nice to have an optional config to scale multiple pods and load balance if necessary. To your point probably best to stay away from more complex ideas like stateful sets and things.

**Comment by jmartin84** [comment]
Hrmm good point, I didn't think of scaling, providing that _would_ allow people to do cool things like stress testing. And I guess it _wouldn't_ be the end of the world to let people mirror their production setup more by letting them specify if they want to use something other than a deployment as an optional config.
